# fly.toml app configuration file generated for social-media-backend on 2023-06-16T22:15:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "social-media-backend"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
